AllCops:
  TargetRubyVersion: 3.0
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Max: 50
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/LineLength:
  Max: 100
Style/Documentation:
  Enabled: false
